#!/bin/sh

WM="${1}"
TIMESTAMP="$(date '+%Y%m%d')T$(TZ='Etc/UTC' date '+%H%M%S')Z"

[ -z "${WM}" ] && WM="sway"

LOG_TARGET="$HOME/.local/share/winit-logs/${WM}-${TIMESTAMP}.log"

args=""

case ${WM} in
	kde) WM="startplasma-wayland" ;;
	plasma) WM="startplasma-wayland" ;;
	sway) args="--unsupported-gpu" ;;
	*) true ;;
esac

if [ "${WM}" = "sway" ]
then
	export XDG_CURRENT_DESKTOP=sway
fi

# Fix Java Apps
export _JAVA_AWT_WM_NONREPARENTING="1"

# Disable .NET Telmetry
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# Fix webkitgtk...
export WEBKIT_DISABLE_COMPOSITING_MODE=1

# nvidia-vaapi
export MOZ_DISABLE_RDD_SANDBOX=1
export LIBVA_DRIVER_NAME=nvidia
export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export NVD_BACKEND=direct
export GBM_BACKEND=nvidia-drm

# Use NSS-DB
export NSS_DEFAULT_DB_TYPE=sql

# Always use LC_COLLATE=C
export LC_COLLATE=C

export XDG_SESSION_TYPE=wayland
export MOZ_ENABLE_WAYLAND=1
export WLR_NO_HARDWARE_CURSORS=1
export ELECTRON_OZONE_PLATFORM_HINT=wayland
export PROTON_ENABLE_WAYLAND=1

# Set ibus as IME
export XMODIFIERS=@im=ibus

dbus-run-session -- "${WM}" ${args} 2>&1 | tee "${LOG_TARGET}"
