#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 0



bspc config border_width         2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a Surf state=tiled
bspc rule -a Zathura:org.pwmt.zathura state=tiled
bspc rule -a Xsane:xsane state=pseudo_tiled

dash "$HOME/.config/bspwm/autostart.sh" > /dev/null 2> /dev/null &
dash "$HOME/.config/polybar/launch.sh" > /dev/null 2> /dev/null & 
