#!/bin/sh

FILE="$(echo '{ "command": ["get_property", "path"] }' | socat - /tmp/mpv.sock | jq .data | sed 's|"||g')"

get_artist()
{
	vorbiscomment -l "$FILE" | grep -i ARTIST | cut -d= -f2
}

get_title()
{
	vorbiscomment -l "$FILE" | grep -i TITLE | cut -d= -f2
}

get_output()
{
	pgrep -x mpv-radio > /dev/null || printf '\n' && exit
	printf '🎵 %b by %b' "$(get_title)" "$(get_artist)"
}

get_output
